### ISSUE TITLE
Suggestion: Filled Maps loot table adjustment

### ISSUE THREAD

**Issue by trollsdottir** [FizixInt/Birds-Nests-Treasures#3]
I was mining a desert having your mod installed and got a lot of Village Maps from Bandit Treasure Pouches, all the same (showing me a village I came from 30 blocks away), (like over double chest of them). Seeing as getting so much of them is useless, and trying to write CT script to remake them into clear maps is a) yet impossible or b) above my ability, I thought I mention this.

Maybe the loot tables can be adjusted to include less of filled maps?

**Comment by FizixInt** [comment]
Updated loot tables in 1.0.2
